# Generated by Django 2.1.2 on 2018-10-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(default='', max_length=10)),
                ('screen', models.CharField(default='', max_length=20)),
                ('number_of_seats', models.IntegerField(default='')),
                ('seats_available', models.CharField(default='', max_length=200)),
                ('seats_unavailable', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
