# Generated by Django 2.1.2 on 2018-10-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screen',
            old_name='seats_available',
            new_name='aisle_seats',
        ),
    ]
